CREATE TABLE IF NOT EXISTS `MEMBER` (
      `SEQ`  INT AUTO_INCREMENT COMMENT '유저 번호'
    , `MEM_ID`  VARCHAR(256) NOT NULL COMMENT '유저 아이디'
    , `NAME`   VARCHAR(64) NOT NULL COMMENT '유저 이름'
    , `NICK_NAME`   VARCHAR(128) NOT NULL COMMENT '유저 별명'
    , `PWD`   VARCHAR(256) NOT NULL COMMENT '유저 비밀번호'
    , `PHN_NUM`   VARCHAR(64) NOT NULL COMMENT '유저 핸드폰번호'
    , `EMAIL`   VARCHAR(256) NOT NULL COMMENT '유저 이메일'
    , `SEX`   ENUM('F','M','X') NOT NULL DEFAULT 'X' COMMENT '유저 성별 ( x : 미입력 )'
    , `REG_DATE`  DATETIME NOT NULL DEFAULT NOW()  COMMENT '가입일자'
    , `UPT_DATE`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '정보 수정일자'
    ,  PRIMARY KEY (`SEQ`)
    ,  UNIQUE INDEX UNI_MEMBER_01 (`MEM_ID`)
    ) COMMENT '유저 정보 테이블'
;